DOMAIN = "amazon_order_status"

CONF_EMAIL = "email"
CONF_IMAP_SERVER = "imap_server"
CONF_IMAP_PORT = "imap_port"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_POLL_INTERVAL = "poll_interval"
CONF_MARK_AS_READ = "mark_as_read"
CONF_DELIVERED_RETENTION_DAYS = "delivered_retention_days"
CONF_IMAP_FOLDER = "imap_folder"
CONF_INITIAL_SCAN_DAYS = "initial_scan_days"
CONF_REQUIRE_AMAZON_SENDER = "require_amazon_sender"
CONF_EXPOSE_ORDER_ID = "expose_order_id"
CONF_EXPOSE_ITEM_TITLE = "expose_item_title"
CONF_EXPOSE_TRACKING_URL = "expose_tracking_url"
CONF_EXPOSE_DELIVERY_DETAILS = "expose_delivery_details"
CONF_EXPOSE_CARRIER = "expose_carrier"
CONF_EXPOSE_ITEM_IMAGE = "expose_item_image"
CONF_EXPOSE_PARSER_DEBUG = "expose_parser_debug"
ERROR_CANNOT_CONNECT = "cannot_connect"
ERROR_INVALID_AUTH = "invalid_auth"

SERVICE_PURGE_ORDER = "purge_order"
SERVICE_RESCAN = "rescan"
SERVICE_SET_STATUS = "set_status"
SERVICE_MARK_DELIVERED = "mark_delivered"
SERVICE_IGNORE_ORDER = "ignore_order"
SERVICE_RESTORE_ORDER = "restore_order"
ATTR_ORDER_ID = "order_id"
ATTR_STATUS = "status"
ATTR_SHIPMENT_ID = "shipment_id"
ATTR_DELIVERED_AT = "delivered_at"
ATTR_DAYS = "days"
ATTR_CLEAR_EXISTING = "clear_existing"
ATTR_CONFIG_ENTRY_ID = "config_entry_id"

DEFAULT_POLL_INTERVAL = 1800  # 30 minutes
